### ISSUE TITLE
Display each post's time

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcode2018-term3#11]
**This task can only be done after #4**
# PART 1

Now that posts are objects, we can add other information to them.

We're going to give each post a time stamp.
- [x] When a post is saved on the server (index.js), as well as saving the message into `post.message`, create a new name-value pair like this: `post.time = "test";`
- [x] Restart you server and test that it's working: in your web browser, post some new messages, then go to http://localhost:3000/posts and look at the raw list of posts. You should see that each post now has a time as well as a message.
- [x] Instead of always setting the time to "test", get the actual date and time - try googling "how do i get the current date in javascript"… if you get stuck for more than 5 minutes, ask for help :)
- [x] Now in feed.html add the post.time so it displays after the post.message. Find the line that creates the `postHTML` variable and add this to the HTML that's added:

```javascript
+ '  <div class="time">time goes here</div>';
```

Test that that displays 'time goes here' in the place where you want the time to appear.

Now, you'll need some careful use of quotation marks and pluses to make javascript include the actual `post.time` inside the tags. Look at the nearby code for reference!

After this change, when you look at http://localhost:3000/feed.html you should see the time for each post - but it's not pretty yet.

# PART 2

Working in _feed.html_

Right now, our timestamp should like this: `2015-09-09T03:42:18.991Z`. Only good if you are a robot  🤖

We can make that nicer, but it will take a lot of code. _Fortunately, someone else has already written the code for us!_ I found a plugin that will work, it's called timeago.js.

- [x] Download timeago.min.js from here: https://raw.githubusercontent.com/hustcc/timeago.js/master/dist/timeago.min.js
- [x] Move timeago.min.js into our project's public folder.
- [x] Include the script in our feed by adding this link to the _head_ section of feed.html

`<script src="/timeago.min.js"></script>`

(It should go just below the other `<script>` line in the head section)

Now your web browser will include that script every time the feed is loaded.

The script gives us some new commands. (The full documentation is at https://github.com/hustcc/timeago.js if you need to look up something that's not written here.)

- [x] to display the post time nicely, replace `post.time` with this:

`new timeago().format(post.time)`

- [x] check that your times are now pretty! They should say something like "11 minutes ago"

# PART 3

It's kind of confusing that the time is the same color as the text and author name.

Let's give the time some CSS rules so it displays differently.
- [x] Add a css rule to `style.css` that makes the time display in a different colour.

Check the feed to see that the time is now in a different colour.

**Comment by canelaferrara** [comment]
Done!
